### ISSUE TITLE
Add topics to help with cataloguing 

### ISSUE THREAD

**Issue by JonathanHope42** [NHSDigital/Smoking-Drinking-and-Drug-Use-Report-Code#1]
Please could you add the topics 'nhs-england-publication' and 'reproduceable-analytical-pipelines' to this repo  
 [Guidance](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)

**Comment by LELLIS87** [comment]
Added 'nhs-england' versions of existing topics - settled for 'reproducible-analytical-pipeline' as that already exists, but can change if needed
